### ISSUE TITLE
Additional one-liner labels

### ISSUE THREAD

**Issue by thegritgrid** [ecogex/ai-label#6]
Hey, I used your labels in my AI work but for better integration in the layouts I changed it to on one text line. Maybe you can add them to the project. I think it will be helful for other users. 
![AI-LABEL_BLACK](https://github.com/ecogex/ai-label/assets/138512287/6f80ac59-c33b-488e-8b06-71d9a6750b9f)
![AI-LABEL_BLACK](https://github.com/ecogex/ai-label/assets/138512287/c66b0716-b03c-4d60-b919-470e46bb2f30)
![AI-LABEL_WHITE](https://github.com/ecogex/ai-label/assets/138512287/c5311240-42c8-4c4f-911a-cdee51b4042c)
![AI-LABEL_WHITE](https://github.com/ecogex/ai-label/assets/138512287/d3016825-0d15-4d23-a26d-95beb8470ef9)

**Comment by ecogex** [comment]
Thank you for the images. We will close that issue as many different derivations can be done from the SVG source and we definitely encourage it, but we want to keep the image pack and the page simple so it is clear enough for visitors, and easy to update for us and collaborators.
